[DG22-2617] setup cypress test to access localhost application in github workflow

diff --git a/.github/workflows/build-deploy-dev.yml b/.github/workflows/build-deploy-dev.yml
--- a/.github/workflows/build-deploy-dev.yml
+++ b/.github/workflows/build-deploy-dev.yml
@@ -12,103 +12,173 @@ env:
   REACT_APP_REGISTRY_API_BASE_URL: '${{ secrets.REACT_APP_REGISTRY_API_BASE_URL_DEV }}'
 
 jobs:
-  build-and-deploy:
-    name: Build and deploy
-    runs-on: ubuntu-latest
-
-    steps:
-      - uses: actions/checkout@v2
-
-      - name: Install Node.js
-        uses: actions/setup-node@v1
-        with:
-          node-version: 14.x
-
-      - name: Install Yarn
-        run: npm install -g yarn
-
-      - name: Install tools
-        run: |
-          if ! command -v azcopy &> /dev/null
-          then
-            echo "azcopy not found, installing..."
-            curl -L https://aka.ms/downloadazcopy-v10-linux | \
-            sudo tar --strip-components=1 -C /usr/local/bin/ --no-same-owner --exclude=*.txt -xzvf -
-            sudo ln -s /usr/local/bin/azcopy /usr/local/bin/azcopy10
-          fi
-
-      - name: Build website
-        run: |
-          # Install all npm packages
-          YARN_IGNORE_ENGINES=true yarn install --frozen-lockfile
-
-          export REACT_APP_BUILD_VERSION=$(date +'%Y%m%d-%H%M%S')
-
-          # Create .env file
-          touch ./.env
-          echo "REACT_APP_OPENFISCA_BASE_URL=$REACT_APP_OPENFISCA_BASE_URL" >> ./.env
-          echo "REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL" >> ./.env
-          echo "REACT_APP_REGISTRY_API_BASE_URL=$REACT_APP_REGISTRY_API_BASE_URL" >> ./.env
-
-          # Build all the JS files for the Drupal
-          yarn run dist-build
-          # Build the react pages
-          yarn run build
-
-          # Prepare dist files to versioned directory
-          mkdir -p ./build/dist/$REACT_APP_BUILD_VERSION
-          cp -R ./dist/* ./build/dist/$REACT_APP_BUILD_VERSION/
-
-          # Prepare dist files to latest directory
-          mkdir -p ./build/dist/latest
-          cp -R ./dist/* ./build/dist/latest/
-
-          # Copy poc acp list folder
-          cp -R ./poc_acp/* ./build/dist/latest/
-
-          # Copy dynamic loader script
-          cp ./src/dynamic-loader.js ./build/dist/latest/
-
-      - name: Deploy to Azure
-        uses: TravisSpomer/deploy-to-azure-storage@v1.4.0
-        with:
-          source-path: build
-          cleanup: false
-          sas-url: ${{ secrets.DEPLOY_SAS_URL_DEV }}
-
   test:
-    name: Run automated testing with Cypress
-    needs: ['build-and-deploy']
+    name: Run Test
     runs-on: ubuntu-latest
-
-    container:
-      image: cypress/browsers:node-24.12.0-chrome-143.0.7499.109-1-ff-146.0-edge-143.0.3650.80-1
-
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout
+        uses: actions/checkout@v4
 
-      - name: Install dependencies
+      - name: Create env file from secrets
+        run: |
+          echo "REACT_APP_OPENFISCA_BASE_URL=$REACT_APP_OPENFISCA_BASE_URL" >> .env
+          echo "REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL" >> .env
+          echo "REACT_APP_REGISTRY_API_BASE_URL=$REACT_APP_REGISTRY_API_BASE_URL" >> .env
+
+      - name: Start app with Docker Compose
+        run: docker compose up -d
+
+      # switch 
+      - name: Setup Node for Cypress
+        uses: actions/setup-node@v6
+        with:
+          node-version: 24
+
+      # 1. Lock Chrome version
+      - name: Setup Chrome 143
+        uses: browser-actions/setup-chrome@v1
+        with:
+          chrome-version: 143
+
+      - name: Install Cypress dependencies
         working-directory: packages/test
         run: npm ci
 
       - name: Run Cypress
-        working-directory: packages/test
+        uses: cypress-io/github-action@v6
+        with:
+          working-directory: packages/test
+          wait-on: 'http://localhost:3000'
+          wait-on-timeout: 60
+          browser: chrome
         env:
-          CYPRESS_BASE_URL: 'https://auesfgracessstgdev.z8.web.core.windows.net'
-        run: npx cypress run --browser chrome
+          CYPRESS_BASE_URL: http://localhost:3000
 
-      - name: 'Cypress Upload Screenshots'
-        uses: 'actions/upload-artifact@v4'
-        with:
-          name: 'cypress-screenshots'
-          path: './packages/test/cypress/screenshots'
-          overwrite: true
-        if: always()
+      # - uses: actions/checkout@v4
 
-      - name: 'Cypress Upload Videos'
-        uses: 'actions/upload-artifact@v4'
-        with:
-          name: 'cypress-videos'
-          path: './packages/test/cypress/videos'
-          overwrite: true
-        if: always()
+      # - name: Install dependencies
+      #   working-directory: packages/test
+      #   run: npm ci
+
+      # - name: Run Cypress
+      #   working-directory: packages/test
+      #   env:
+      #     CYPRESS_BASE_URL: 'https://auesfgracessstgdev.z8.web.core.windows.net'
+      #   run: npx cypress run --browser chrome
+
+      # - name: 'Cypress Upload Screenshots'
+      #   uses: 'actions/upload-artifact@v4'
+      #   with:
+      #     name: 'cypress-screenshots'
+      #     path: './packages/test/cypress/screenshots'
+      #     overwrite: true
+      #   if: always()
+
+      # - name: 'Cypress Upload Videos'
+      #   uses: 'actions/upload-artifact@v4'
+      #   with:
+      #     name: 'cypress-videos'
+      #     path: './packages/test/cypress/videos'
+      #     overwrite: true
+      #   if: always()
+
+  # build-and-deploy:
+  #   name: Build and deploy
+  #   runs-on: ubuntu-latest
+
+  #   steps:
+  #     - uses: actions/checkout@v2
+
+  #     - name: Install Node.js
+  #       uses: actions/setup-node@v1
+  #       with:
+  #         node-version: 14.x
+
+  #     - name: Install Yarn
+  #       run: npm install -g yarn
+
+  #     - name: Install tools
+  #       run: |
+  #         if ! command -v azcopy &> /dev/null
+  #         then
+  #           echo "azcopy not found, installing..."
+  #           curl -L https://aka.ms/downloadazcopy-v10-linux | \
+  #           sudo tar --strip-components=1 -C /usr/local/bin/ --no-same-owner --exclude=*.txt -xzvf -
+  #           sudo ln -s /usr/local/bin/azcopy /usr/local/bin/azcopy10
+  #         fi
+
+  #     - name: Build website
+  #       run: |
+  #         # Install all npm packages
+  #         YARN_IGNORE_ENGINES=true yarn install --frozen-lockfile
+
+  #         export REACT_APP_BUILD_VERSION=$(date +'%Y%m%d-%H%M%S')
+
+  #         # Create .env file
+  #         touch ./.env
+  #         echo "REACT_APP_OPENFISCA_BASE_URL=$REACT_APP_OPENFISCA_BASE_URL" >> ./.env
+  #         echo "REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL" >> ./.env
+  #         echo "REACT_APP_REGISTRY_API_BASE_URL=$REACT_APP_REGISTRY_API_BASE_URL" >> ./.env
+
+  #         # Build all the JS files for the Drupal
+  #         yarn run dist-build
+  #         # Build the react pages
+  #         yarn run build
+
+  #         # Prepare dist files to versioned directory
+  #         mkdir -p ./build/dist/$REACT_APP_BUILD_VERSION
+  #         cp -R ./dist/* ./build/dist/$REACT_APP_BUILD_VERSION/
+
+  #         # Prepare dist files to latest directory
+  #         mkdir -p ./build/dist/latest
+  #         cp -R ./dist/* ./build/dist/latest/
+
+  #         # Copy poc acp list folder
+  #         cp -R ./poc_acp/* ./build/dist/latest/
+
+  #         # Copy dynamic loader script
+  #         cp ./src/dynamic-loader.js ./build/dist/latest/
+
+  #     - name: Deploy to Azure
+  #       uses: TravisSpomer/deploy-to-azure-storage@v1.4.0
+  #       with:
+  #         source-path: build
+  #         cleanup: false
+  #         sas-url: ${{ secrets.DEPLOY_SAS_URL_DEV }}
+
+  # test:
+  #   name: Run automated testing with Cypress
+  #   needs: ['build-and-deploy']
+  #   runs-on: ubuntu-latest
+
+  #   container:
+  #     image: cypress/browsers:node-24.12.0-chrome-143.0.7499.109-1-ff-146.0-edge-143.0.3650.80-1
+
+  #   steps:
+  #     - uses: actions/checkout@v4
+
+  #     - name: Install dependencies
+  #       working-directory: packages/test
+  #       run: npm ci
+
+  #     - name: Run Cypress
+  #       working-directory: packages/test
+  #       env:
+  #         CYPRESS_BASE_URL: 'https://auesfgracessstgdev.z8.web.core.windows.net'
+  #       run: npx cypress run --browser chrome
+
+  #     - name: 'Cypress Upload Screenshots'
+  #       uses: 'actions/upload-artifact@v4'
+  #       with:
+  #         name: 'cypress-screenshots'
+  #         path: './packages/test/cypress/screenshots'
+  #         overwrite: true
+  #       if: always()
+
+  #     - name: 'Cypress Upload Videos'
+  #       uses: 'actions/upload-artifact@v4'
+  #       with:
+  #         name: 'cypress-videos'
+  #         path: './packages/test/cypress/videos'
+  #         overwrite: true
+  #       if: always()
