[DG22-2386] try remove step install azcopy that causing an error

diff --git a/.github/workflows/build-deploy-dev.yml b/.github/workflows/build-deploy-dev.yml
--- a/.github/workflows/build-deploy-dev.yml
+++ b/.github/workflows/build-deploy-dev.yml
@@ -27,15 +27,15 @@ jobs:
       - name: Install Yarn
         run: npm install -g yarn
 
-      - name: Install tools
-        run: |
-          if ! command -v azcopy &> /dev/null
-          then
-            echo "azcopy not found, installing..."
-            curl -L https://aka.ms/downloadazcopy-v10-linux | \
-            sudo tar --strip-components=1 -C /usr/local/bin/ --no-same-owner --exclude=*.txt -xzvf -
-            sudo ln -s /usr/local/bin/azcopy /usr/local/bin/azcopy10
-          fi
+#      - name: Install tools
+#        run: |
+#          if ! command -v azcopy &> /dev/null
+#          then
+#            echo "azcopy not found, installing..."
+#            curl -L https://aka.ms/downloadazcopy-v10-linux | \
+#            sudo tar --strip-components=1 -C /usr/local/bin/ --no-same-owner --exclude=*.txt -xzvf -
+#            sudo ln -s /usr/local/bin/azcopy /usr/local/bin/azcopy10
+#          fi
 
       - name: Build website
         run: |
