[DG22-2386] revert back step install tools on dev workflow

diff --git a/.github/workflows/build-deploy-dev.yml b/.github/workflows/build-deploy-dev.yml
--- a/.github/workflows/build-deploy-dev.yml
+++ b/.github/workflows/build-deploy-dev.yml
@@ -29,10 +29,13 @@ jobs:
 
       - name: Install tools
         run: |
-          wget -O azcopy.tar.gz https://aka.ms/downloadazcopy-v10-linux
-          tar -xf azcopy.tar.gz
-          sudo cp ./azcopy_linux_amd64_*/azcopy /usr/local/bin/
-          azcopy --version
+          if ! command -v azcopy &> /dev/null
+          then
+            echo "azcopy not found, installing..."
+            curl -L https://aka.ms/downloadazcopy-v10-linux | \
+            sudo tar --strip-components=1 -C /usr/local/bin/ --no-same-owner --exclude=*.txt -xzvf -
+            sudo ln -s /usr/local/bin/azcopy /usr/local/bin/azcopy10
+          fi
 
       - name: Build website
         run: |
