[DG22-2617] change cypress docker image in dev workflow

diff --git a/.github/workflows/build-deploy-dev.yml b/.github/workflows/build-deploy-dev.yml
--- a/.github/workflows/build-deploy-dev.yml
+++ b/.github/workflows/build-deploy-dev.yml
@@ -12,77 +12,77 @@ env:
   REACT_APP_REGISTRY_API_BASE_URL: '${{ secrets.REACT_APP_REGISTRY_API_BASE_URL_DEV }}'
 
 jobs:
-  build-and-deploy:
-    name: Build and deploy
-    runs-on: ubuntu-latest
+  # build-and-deploy:
+  #   name: Build and deploy
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - uses: actions/checkout@v2
+  #   steps:
+  #     - uses: actions/checkout@v2
 
-      - name: Install Node.js
-        uses: actions/setup-node@v1
-        with:
-          node-version: 14.x
+  #     - name: Install Node.js
+  #       uses: actions/setup-node@v1
+  #       with:
+  #         node-version: 14.x
 
-      - name: Install Yarn
-        run: npm install -g yarn
+  #     - name: Install Yarn
+  #       run: npm install -g yarn
 
-      - name: Install tools
-        run: |
-          if ! command -v azcopy &> /dev/null
-          then
-            echo "azcopy not found, installing..."
-            curl -L https://aka.ms/downloadazcopy-v10-linux | \
-            sudo tar --strip-components=1 -C /usr/local/bin/ --no-same-owner --exclude=*.txt -xzvf -
-            sudo ln -s /usr/local/bin/azcopy /usr/local/bin/azcopy10
-          fi
+  #     - name: Install tools
+  #       run: |
+  #         if ! command -v azcopy &> /dev/null
+  #         then
+  #           echo "azcopy not found, installing..."
+  #           curl -L https://aka.ms/downloadazcopy-v10-linux | \
+  #           sudo tar --strip-components=1 -C /usr/local/bin/ --no-same-owner --exclude=*.txt -xzvf -
+  #           sudo ln -s /usr/local/bin/azcopy /usr/local/bin/azcopy10
+  #         fi
 
-      - name: Build website
-        run: |
-          # Install all npm packages
-          YARN_IGNORE_ENGINES=true yarn install --frozen-lockfile
+  #     - name: Build website
+  #       run: |
+  #         # Install all npm packages
+  #         YARN_IGNORE_ENGINES=true yarn install --frozen-lockfile
 
-          export REACT_APP_BUILD_VERSION=$(date +'%Y%m%d-%H%M%S')
+  #         export REACT_APP_BUILD_VERSION=$(date +'%Y%m%d-%H%M%S')
 
-          # Create .env file
-          touch ./.env
-          echo "REACT_APP_OPENFISCA_BASE_URL=$REACT_APP_OPENFISCA_BASE_URL" >> ./.env
-          echo "REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL" >> ./.env
-          echo "REACT_APP_REGISTRY_API_BASE_URL=$REACT_APP_REGISTRY_API_BASE_URL" >> ./.env
+  #         # Create .env file
+  #         touch ./.env
+  #         echo "REACT_APP_OPENFISCA_BASE_URL=$REACT_APP_OPENFISCA_BASE_URL" >> ./.env
+  #         echo "REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL" >> ./.env
+  #         echo "REACT_APP_REGISTRY_API_BASE_URL=$REACT_APP_REGISTRY_API_BASE_URL" >> ./.env
 
-          # Build all the JS files for the Drupal
-          yarn run dist-build
-          # Build the react pages
-          yarn run build
+  #         # Build all the JS files for the Drupal
+  #         yarn run dist-build
+  #         # Build the react pages
+  #         yarn run build
 
-          # Prepare dist files to versioned directory
-          mkdir -p ./build/dist/$REACT_APP_BUILD_VERSION
-          cp -R ./dist/* ./build/dist/$REACT_APP_BUILD_VERSION/
+  #         # Prepare dist files to versioned directory
+  #         mkdir -p ./build/dist/$REACT_APP_BUILD_VERSION
+  #         cp -R ./dist/* ./build/dist/$REACT_APP_BUILD_VERSION/
 
-          # Prepare dist files to latest directory
-          mkdir -p ./build/dist/latest
-          cp -R ./dist/* ./build/dist/latest/
+  #         # Prepare dist files to latest directory
+  #         mkdir -p ./build/dist/latest
+  #         cp -R ./dist/* ./build/dist/latest/
 
-          # Copy poc acp list folder
-          cp -R ./poc_acp/* ./build/dist/latest/
+  #         # Copy poc acp list folder
+  #         cp -R ./poc_acp/* ./build/dist/latest/
 
-          # Copy dynamic loader script
-          cp ./src/dynamic-loader.js ./build/dist/latest/
+  #         # Copy dynamic loader script
+  #         cp ./src/dynamic-loader.js ./build/dist/latest/
 
-      - name: Deploy to Azure
-        uses: TravisSpomer/deploy-to-azure-storage@v1.4.0
-        with:
-          source-path: build
-          cleanup: false
-          sas-url: ${{ secrets.DEPLOY_SAS_URL_DEV }}
+  #     - name: Deploy to Azure
+  #       uses: TravisSpomer/deploy-to-azure-storage@v1.4.0
+  #       with:
+  #         source-path: build
+  #         cleanup: false
+  #         sas-url: ${{ secrets.DEPLOY_SAS_URL_DEV }}
 
   test:
     name: Run automated testing with Cypress
-    needs: ['build-and-deploy']
+    # needs: ['build-and-deploy']
     runs-on: ubuntu-latest
 
     container:
-      image: cypress/browsers:node-24.12.0-chrome-143
+      image: cypress/browsers:node-24.12.0-chrome-143.0.7499.109-1-ff-146.0-edge-143.0.3650.80-1
 
     steps:
       - uses: actions/checkout@v4
@@ -112,62 +112,3 @@ jobs:
           path: './packages/test/cypress/videos'
           overwrite: true
         if: always()
-
-  # test:
-  #   name: Run automated testing with cypress
-  #   needs: ["build-and-deploy"]
-  #   runs-on: "ubuntu-latest"
-  #   container:
-  #     image: "cypress/browsers:node-24.12.0-chrome-143.0.7499.109-1-ff-146.0-edge-143.0.3650.80-1"
-
-  #   steps:
-  #     - name: Checkout
-  #       uses: actions/checkout@v4
-
-  #     - name: Install Cypress dependencies
-  #       working-directory: cypress
-  #       run: |
-  #         npm ci
-
-  #     - name: Cypress run
-  #       uses: cypress-io/github-action@v6
-  #       working-directory: cypress
-  #       with:
-  #         start: npm run test
-  #         browser: chrome
-
-  # - name: "Setup node"
-  #   uses: "actions/setup-node@v3"
-  #   with:
-  #     node-version-file: ".nvmrc"
-  #   if: always()
-  # - name: "Install tools"
-  #   run: |
-  #     # Install packages
-  #     npm ci
-  # - name: "Cypress Run All Tests"
-  #   uses: "cypress-io/github-action@v5"
-  #   with:
-  #     install: false
-  #     working-directory: "./frontend-next"
-  #     browser: "chrome"
-  #     config: "pageLoadTimeout=100000"
-  #   env:
-  #     CYPRESS_BASE_URL: "${{ needs.deploy.outputs.VERCEL_DEPLOYMENT_URL }}"
-  #     CYPRESS_ENABLE_TEST_ISR: "true"
-  #     CYPRESS_DRUPAL_REVALIDATE_SECRET: "${{ secrets.CYPRESS_DRUPAL_REVALIDATE_SECRET }}"
-  #   if: always()
-  # - name: "Cypress Upload Screenshots"
-  #   uses: "actions/upload-artifact@v4"
-  #   with:
-  #     name: "cypress-screenshots"
-  #     path: "./frontend-next/cypress/screenshots"
-  #     overwrite: true
-  #   if: always()
-  # - name: "Cypress Upload Videos"
-  #   uses: "actions/upload-artifact@v4"
-  #   with:
-  #     name: "cypress-videos"
-  #     path: "./frontend-next/cypress/videos"
-  #     overwrite: true
-  #   if: always()
