[DG22-2692] adjust current dev Github workflow for testing purpose

diff --git a/.github/workflows/build-deploy-dev.yml b/.github/workflows/build-deploy-dev.yml
--- a/.github/workflows/build-deploy-dev.yml
+++ b/.github/workflows/build-deploy-dev.yml
@@ -2,162 +2,182 @@ name: Build and Deploy to DEV
 
 on:
   workflow_dispatch:
-  pull_request:
-    types: [opened, synchronize, labeled]
-    branches:
-      - nonprod
-  push:
-    branches:
-      - nonprod
-
-env:
-  REACT_APP_OPENFISCA_BASE_URL: '${{ secrets.REACT_APP_OPENFISCA_BASE_URL_DEV }}'
-  REACT_APP_API_BASE_URL: '${{ secrets.REACT_APP_API_BASE_URL_DEV }}'
-  REACT_APP_REGISTRY_API_BASE_URL: '${{ secrets.REACT_APP_REGISTRY_API_BASE_URL_DEV }}'
 
 jobs:
   test:
-    name: Run Test
-    if: |
-      contains(github.event.pull_request.labels.*.name, 'run-test') || 
-      github.event.action == 'opened' ||
-      github.event_name == 'push' ||
-      github.event_name == 'workflow_dispatch'
-    runs-on: self-hosted
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+    uses: ./.github/workflows/main.yml
+    with:
+      run-test: true
+      run-deploy: false
+      upload-report-github: true
+    secrets: 
+      REACT_APP_OPENFISCA_BASE_URL: ${{ secrets.REACT_APP_OPENFISCA_BASE_URL_DEV }}
+      REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL_DEV }}
+      REACT_APP_REGISTRY_API_BASE_URL: ${{ secrets.REACT_APP_REGISTRY_API_BASE_URL_DEV }}
+      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_DEV }}
+      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP_DEV }}
+      AZURE_VM_NAME: ${{ secrets.AZURE_VM_NAME_DEV }}
+      COMMUNICATION_SERVICES_CONNECTION_STRING: ${{ secrets.COMMUNICATION_SERVICES_CONNECTION_STRING }}
+      COMMUNICATION_SERVICES_EMAIL_SENDER_DOMAIN: ${{ secrets.COMMUNICATION_SERVICES_EMAIL_SENDER_DOMAIN }}
+      GH_TOKEN: ${{ secrets.GH_TOKEN }}
 
-      - name: Create env file from secrets
-        run: |
-          echo "REACT_APP_OPENFISCA_BASE_URL=$REACT_APP_OPENFISCA_BASE_URL" >> .env
-          echo "REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL" >> .env
-          echo "REACT_APP_REGISTRY_API_BASE_URL=$REACT_APP_REGISTRY_API_BASE_URL" >> .env
+  # pull_request:
+  #   types: [opened, synchronize, labeled]
+  #   branches:
+  #     - nonprod
+  # push:
+  #   branches:
+  #     - nonprod
 
-      - name: Start app with Docker Compose
-        working-directory: .
-        run: docker compose up --build -d
+# env:
+#   REACT_APP_OPENFISCA_BASE_URL: '${{ secrets.REACT_APP_OPENFISCA_BASE_URL_DEV }}'
+#   REACT_APP_API_BASE_URL: '${{ secrets.REACT_APP_API_BASE_URL_DEV }}'
+#   REACT_APP_REGISTRY_API_BASE_URL: '${{ secrets.REACT_APP_REGISTRY_API_BASE_URL_DEV }}'
 
-      - name: Setup Node for Cypress
-        uses: actions/setup-node@v6
-        with:
-          node-version: 24
+# jobs:
+#   test:
+#     name: Run Test
+#     if: |
+#       contains(github.event.pull_request.labels.*.name, 'run-test') || 
+#       github.event.action == 'opened' ||
+#       github.event_name == 'push' ||
+#       github.event_name == 'workflow_dispatch'
+#     runs-on: self-hosted
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v4
 
-      # 1. Lock Chrome version
-      - name: Setup Chrome 143
-        uses: browser-actions/setup-chrome@v1
-        with:
-          chrome-version: 143
+#       - name: Create env file from secrets
+#         run: |
+#           echo "REACT_APP_OPENFISCA_BASE_URL=$REACT_APP_OPENFISCA_BASE_URL" >> .env
+#           echo "REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL" >> .env
+#           echo "REACT_APP_REGISTRY_API_BASE_URL=$REACT_APP_REGISTRY_API_BASE_URL" >> .env
 
-      - name: Install Cypress dependencies
-        working-directory: packages/test
-        run: yarn install --frozen-lockfile
+#       - name: Start app with Docker Compose
+#         working-directory: .
+#         run: docker compose up --build -d
 
-      - name: Cleanup old Cypress assets
-        run: |
-          rm -rf cypress/screenshots/*
-          rm -rf cypress/videos/*
+#       - name: Setup Node for Cypress
+#         uses: actions/setup-node@v6
+#         with:
+#           node-version: 24
 
-      - name: Run Cypress
-        uses: cypress-io/github-action@v6
-        with:
-          working-directory: packages/test
-          wait-on: 'http://localhost:3000'
-          wait-on-timeout: 60
-          browser: chrome-for-testing
-        env:
-          EXCEL_PATH: /home/azureuser/data.xlsx
-          SEND_REPORT_TO_EMAIL: ${{ github.event_name == 'workflow_dispatch' && 'true' || 'false' }}
-          UPLOAD_REPORT_TO_GITHUB: ${{ github.event_name == 'workflow_dispatch' && 'true' || 'false' }}
-          COMMUNICATION_SERVICES_CONNECTION_STRING: ${{ secrets.COMMUNICATION_SERVICES_CONNECTION_STRING }}
-          COMMUNICATION_SERVICES_EMAIL_SENDER_DOMAIN: ${{ secrets.COMMUNICATION_SERVICES_EMAIL_SENDER_DOMAIN }}
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#       # 1. Lock Chrome version
+#       - name: Setup Chrome 143
+#         uses: browser-actions/setup-chrome@v1
+#         with:
+#           chrome-version: 143
 
-      - name: Upload screenshot
-        uses: actions/upload-artifact@v6
-        if: failure()
-        with:
-          name: cypress-screenshots
-          path: packages/test/cypress/screenshots/
-          if-no-files-found: ignore
-          retention-days: 7
+#       - name: Install Cypress dependencies
+#         working-directory: packages/test
+#         run: yarn install --frozen-lockfile
 
-      - name: Upload videos
-        uses: actions/upload-artifact@v6
-        if: failure()
-        with:
-          name: cypress-videos
-          path: packages/test/cypress/videos/
-          if-no-files-found: ignore
-          retention-days: 7
+#       - name: Cleanup old Cypress assets
+#         run: |
+#           rm -rf cypress/screenshots/*
+#           rm -rf cypress/videos/*
 
-      - name: Tear down docker
-        if: always()
-        run: docker compose down
-        working-directory: .
+#       - name: Run Cypress
+#         uses: cypress-io/github-action@v6
+#         with:
+#           working-directory: packages/test
+#           wait-on: 'http://localhost:3000'
+#           wait-on-timeout: 60
+#           browser: chrome-for-testing
+#         env:
+#           EXCEL_PATH: /home/azureuser/data.xlsx
+#           SEND_REPORT_TO_EMAIL: ${{ github.event_name == 'workflow_dispatch' && 'true' || 'false' }}
+#           UPLOAD_REPORT_TO_GITHUB: ${{ github.event_name == 'workflow_dispatch' && 'true' || 'false' }}
+#           COMMUNICATION_SERVICES_CONNECTION_STRING: ${{ secrets.COMMUNICATION_SERVICES_CONNECTION_STRING }}
+#           COMMUNICATION_SERVICES_EMAIL_SENDER_DOMAIN: ${{ secrets.COMMUNICATION_SERVICES_EMAIL_SENDER_DOMAIN }}
+#           GH_TOKEN: ${{ secrets.GH_TOKEN }}
 
-  build-and-deploy:
-    name: Build and deploy
-    needs: test
-    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
-    runs-on: ubuntu-latest
+#       - name: Upload screenshot
+#         uses: actions/upload-artifact@v6
+#         if: failure()
+#         with:
+#           name: cypress-screenshots
+#           path: packages/test/cypress/screenshots/
+#           if-no-files-found: ignore
+#           retention-days: 7
 
-    steps:
-      - uses: actions/checkout@v2
+#       - name: Upload videos
+#         uses: actions/upload-artifact@v6
+#         if: failure()
+#         with:
+#           name: cypress-videos
+#           path: packages/test/cypress/videos/
+#           if-no-files-found: ignore
+#           retention-days: 7
 
-      - name: Install Node.js
-        uses: actions/setup-node@v1
-        with:
-          node-version: 14.x
+#       - name: Tear down docker
+#         if: always()
+#         run: docker compose down
+#         working-directory: .
 
-      - name: Install Yarn
-        run: npm install -g yarn
+#   build-and-deploy:
+#     name: Build and deploy
+#     needs: test
+#     # if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
+#     if: github.event_name == 'push'
+#     runs-on: ubuntu-latest
 
-      - name: Install tools
-        run: |
-          if ! command -v azcopy &> /dev/null
-          then
-            echo "azcopy not found, installing..."
-            curl -L https://aka.ms/downloadazcopy-v10-linux | \
-            sudo tar --strip-components=1 -C /usr/local/bin/ --no-same-owner --exclude=*.txt -xzvf -
-            sudo ln -s /usr/local/bin/azcopy /usr/local/bin/azcopy10
-          fi
+#     steps:
+#       - uses: actions/checkout@v2
 
-      - name: Build website
-        run: |
-          # Install all npm packages
-          YARN_IGNORE_ENGINES=true yarn install --frozen-lockfile
+#       - name: Install Node.js
+#         uses: actions/setup-node@v1
+#         with:
+#           node-version: 14.x
 
-          export REACT_APP_BUILD_VERSION=$(date +'%Y%m%d-%H%M%S')
+#       - name: Install Yarn
+#         run: npm install -g yarn
 
-          # Create .env file
-          touch ./.env
-          echo "REACT_APP_OPENFISCA_BASE_URL=$REACT_APP_OPENFISCA_BASE_URL" >> ./.env
-          echo "REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL" >> ./.env
-          echo "REACT_APP_REGISTRY_API_BASE_URL=$REACT_APP_REGISTRY_API_BASE_URL" >> ./.env
+#       - name: Install tools
+#         run: |
+#           if ! command -v azcopy &> /dev/null
+#           then
+#             echo "azcopy not found, installing..."
+#             curl -L https://aka.ms/downloadazcopy-v10-linux | \
+#             sudo tar --strip-components=1 -C /usr/local/bin/ --no-same-owner --exclude=*.txt -xzvf -
+#             sudo ln -s /usr/local/bin/azcopy /usr/local/bin/azcopy10
+#           fi
 
-          # Build all the JS files for the Drupal
-          yarn run dist-build
-          # Build the react pages
-          yarn run build
+#       - name: Build website
+#         run: |
+#           # Install all npm packages
+#           YARN_IGNORE_ENGINES=true yarn install --frozen-lockfile
 
-          # Prepare dist files to versioned directory
-          mkdir -p ./build/dist/$REACT_APP_BUILD_VERSION
-          cp -R ./dist/* ./build/dist/$REACT_APP_BUILD_VERSION/
+#           export REACT_APP_BUILD_VERSION=$(date +'%Y%m%d-%H%M%S')
 
-          # Prepare dist files to latest directory
-          mkdir -p ./build/dist/latest
-          cp -R ./dist/* ./build/dist/latest/
+#           # Create .env file
+#           touch ./.env
+#           echo "REACT_APP_OPENFISCA_BASE_URL=$REACT_APP_OPENFISCA_BASE_URL" >> ./.env
+#           echo "REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL" >> ./.env
+#           echo "REACT_APP_REGISTRY_API_BASE_URL=$REACT_APP_REGISTRY_API_BASE_URL" >> ./.env
 
-          # Copy poc acp list folder
-          cp -R ./poc_acp/* ./build/dist/latest/
+#           # Build all the JS files for the Drupal
+#           yarn run dist-build
+#           # Build the react pages
+#           yarn run build
 
-          # Copy dynamic loader script
-          cp ./src/dynamic-loader.js ./build/dist/latest/
+#           # Prepare dist files to versioned directory
+#           mkdir -p ./build/dist/$REACT_APP_BUILD_VERSION
+#           cp -R ./dist/* ./build/dist/$REACT_APP_BUILD_VERSION/
 
-      - name: Deploy to Azure
-        uses: TravisSpomer/deploy-to-azure-storage@v1.4.0
-        with:
-          source-path: build
-          cleanup: false
-          sas-url: ${{ secrets.DEPLOY_SAS_URL_DEV }}
+#           # Prepare dist files to latest directory
+#           mkdir -p ./build/dist/latest
+#           cp -R ./dist/* ./build/dist/latest/
+
+#           # Copy poc acp list folder
+#           cp -R ./poc_acp/* ./build/dist/latest/
+
+#           # Copy dynamic loader script
+#           cp ./src/dynamic-loader.js ./build/dist/latest/
+
+#       - name: Deploy to Azure
+#         uses: TravisSpomer/deploy-to-azure-storage@v1.4.0
+#         with:
+#           source-path: build
+#           cleanup: false
+#           sas-url: ${{ secrets.DEPLOY_SAS_URL_DEV }}
