[DG22-1740] Remove .env file, update readme, update workflow for nonprod and prod

diff --git a/.github/workflows/deploy_to_azure.yml b/.github/workflows/deploy_to_azure.yml
--- a/.github/workflows/deploy_to_azure.yml
+++ b/.github/workflows/deploy_to_azure.yml
@@ -3,7 +3,12 @@ name: Deploy website to Azure
 on:
   workflow_dispatch:
   push:
-    branches: [master]
+    branches: master
+
+env:
+  REACT_APP_OPENFISCA_BASE_URL: "${{ secrets.REACT_APP_OPENFISCA_BASE_URL_PROD }}"
+  REACT_APP_API_BASE_URL: "${{ secrets.REACT_APP_API_BASE_URL_PROD }}"
+  REACT_APP_REGISTRY_API_BASE_URL: "${{ secrets.REACT_APP_REGISTRY_API_BASE_URL_PROD }}"
 
 jobs:
   build-and-deploy:
@@ -18,10 +23,35 @@ jobs:
         with:
           node-version: 14.x
 
+      - name: Install tools
+        run: |
+          if ! command -v azcopy &> /dev/null
+          then
+            echo "azcopy not found, installing..."
+            curl -L https://aka.ms/downloadazcopy-v10-linux | \
+            sudo tar --strip-components=1 -C /usr/local/bin/ --no-same-owner --exclude=*.txt -xzvf -
+            sudo ln -s /usr/local/bin/azcopy /usr/local/bin/azcopy10
+          fi
+
       - name: Build website
         run: |
-          yarn install
-          CI="" yarn run build
+          # Install all npm packages
+          npm install
+
+          # Build all the JS files for the Drupal
+          npm run build-dist
+          # Build the react pages
+          npm run build
+          
+          export BUILD_VERSION=$(date +'%Y%m%d-%H%M%S')
+
+          # Prepare dist files to versioned directory
+          mkdir -p ./build/dist/$BUILD_VERSION
+          cp -R ./dist/ ./build/dist/$BUILD_VERSION/
+
+          # Prepare dist files to latest directory
+          mkdir -p ./build/dist/latest
+          cp -R ./dist/ ./build/dist/latest/
 
       - name: Deploy to Azure
         uses: TravisSpomer/deploy-to-azure-storage@v1.4.0
