[DG22-1740] Update workflow with dist-build

diff --git a/.github/workflows/deploy_to_azure_testing.yml b/.github/workflows/deploy_to_azure_testing.yml
--- a/.github/workflows/deploy_to_azure_testing.yml
+++ b/.github/workflows/deploy_to_azure_testing.yml
@@ -5,6 +5,11 @@ on:
   push:
     branches: nonprod
 
+env:
+  REACT_APP_OPENFISCA_BASE_URL: '${{ secrets.REACT_APP_OPENFISCA_BASE_URL_DEV }}'
+  REACT_APP_API_BASE_URL: '${{ secrets.REACT_APP_API_BASE_URL_DEV }}'
+  REACT_APP_REGISTRY_API_BASE_URL: '${{ secrets.REACT_APP_REGISTRY_API_BASE_URL_DEV }}'
+
 jobs:
   build-and-deploy:
     name: Build and deploy
@@ -18,12 +23,46 @@ jobs:
         with:
           node-version: 16.x
 
+      - name: Install tools
+        run: |
+          if ! command -v azcopy &> /dev/null
+          then
+            echo "azcopy not found, installing..."
+            curl -L https://aka.ms/downloadazcopy-v10-linux | \
+            sudo tar --strip-components=1 -C /usr/local/bin/ --no-same-owner --exclude=*.txt -xzvf -
+            sudo ln -s /usr/local/bin/azcopy /usr/local/bin/azcopy10
+          fi
+
       - name: Build website
         run: |
+          # Install all npm packages
           npm ci
-          CI="" npm run build
+
+          # Create .env file
+          touch ./.env
+          echo "REACT_APP_OPENFISCA_BASE_URL=$REACT_APP_OPENFISCA_BASE_URL" >> ./.env
+          echo "REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL" >> ./.env
+          echo "REACT_APP_REGISTRY_API_BASE_URL=$REACT_APP_REGISTRY_API_BASE_URL" >> ./.env
+          cat ./.env
+
+          # Build all the JS files for the Drupal
+          npm run dist-build
+          # Build the react pages
+          npm run build
+
+          export REACT_APP_BUILD_VERSION=$(date +'%Y%m%d-%H%M%S')
+
+          # Prepare dist files to versioned directory
+          mkdir -p ./build/dist/$REACT_APP_BUILD_VERSION
+          cp -R ./dist/ ./build/dist/$REACT_APP_BUILD_VERSION/
+
+          # Prepare dist files to latest directory
+          mkdir -p ./build/dist/latest
+          cp -R ./dist/ ./build/dist/latest/
+
       - name: Deploy to Azure
         uses: TravisSpomer/deploy-to-azure-storage@v1.4.0
         with:
           source-path: build
+          cleanup: false
           sas-url: ${{ secrets.DEPLOY_SAS_URL_TESTING }}
